version: 2

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  commit-message:
    prefix: chore
  groups:
    npm-production:
      applies-to: version-updates
      dependency-type: production
      patterns:
      - "*"
    vitest:
      applies-to: version-updates
      patterns:
      - "vitest"
      - "@vitest/*"
    linting:
      applies-to: version-updates
      patterns:
      - "eslint"
      - "eslint-*"
      - "neostandard"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  commit-message:
    prefix: chore
