services:
  fcp-sfd-crm-stub:
    build:
      context: .
      target: development
    ports:
      - '3001:3001'
    environment:
      PORT: 3001
      NODE_ENV: development
    networks:
      - cdp-tenant
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json

################################################################################

networks:
  cdp-tenant:
    driver: bridge
    name: cdp-tenant
