name: fcp-sfd-crm-stub-test

services:
  fcp-sfd-crm-stub:
    build:
      target: development
    command: npm test
    volumes:
      - ./test:/home/node/test
      - ./package.json:/home/node/package.json
      - ./vitest.config.js:/home/node/vitest.config.js
      - ./coverage:/home/node/coverage
