import { STATUS_CODES } from 'node:http'

export const ODATA_ERROR_CONTENT_TYPE =
  'application/json; odata.metadata=minimal'

export const STUB_ERROR_CODE = 'STUB_GENERATED_ERROR'

export const STUB_ERROR_MESSAGE_PREFIX =
  'Generated by fcp-sfd-crm-stub, not Dataverse error text:'

/**
 * Builds a JSON OData error body marked as generated by the stub. Used by both
 * the standalone conditional upsert routes and the `$batch` response builder,
 * as the shape is an OData concern rather than a `$batch` one.
 * @param {number} status - a standard HTTP status code
 * @returns {{ error: { code: string, message: string } }}
 */
export const buildStubErrorBody = (status) => ({
  error: {
    code: STUB_ERROR_CODE,
    message: `${STUB_ERROR_MESSAGE_PREFIX} ${STATUS_CODES[status]}`
  }
})
