import { randomUUID } from 'node:crypto'
import { STATUS_CODES } from 'node:http'

// Dataverse is believed to accept up to 1000 requests in one $batch, but this
// has not been verified against the Dataverse documentation. Change it here if
// the documented limit differs.
export const MAX_BATCH_PARTS = 1000

const CRLF = '\r\n'
const MULTIPART_MIXED = 'multipart/mixed'
const APPLICATION_HTTP = 'application/http'
const BOUNDARY_PARAMETER = 'boundary='
const HTTP_VERSION = 'HTTP/1.1'
const REQUEST_LINE_TOKEN_COUNT = 3
const HTTP_NO_CONTENT = 204
const HTTP_BAD_REQUEST = 400
const URL_RESOLUTION_BASE = 'https://stub.invalid'
const ENTITY_KEY_PATH_PATTERN = /^\/api\/data\/v9\.2\/([a-z_]+)\(([^)]+)\)$/
const ERROR_CONTENT_TYPE = 'application/json; odata.metadata=minimal'
const STUB_ERROR_CODE = 'STUB_GENERATED_ERROR'
const STUB_ERROR_MESSAGE_PREFIX =
  'Generated by fcp-sfd-crm-stub, not Dataverse error text:'

const ERROR_UNSUPPORTED = 'unsupported'
const ERROR_INVALID_JSON = 'invalid_json'
const ERROR_TOO_MANY_PARTS = 'too_many_parts'

class BatchParseError extends Error {
  constructor(reason) {
    super(reason)
    this.reason = reason
  }
}

const unsupported = () => new BatchParseError(ERROR_UNSUPPORTED)

function getMultipartBoundary(contentType) {
  if (typeof contentType !== 'string') {
    return null
  }

  const [mediaType, ...parameters] = contentType
    .split(';')
    .map((segment) => segment.trim())
  if (mediaType.toLowerCase() !== MULTIPART_MIXED) {
    return null
  }

  const boundaryParameter = parameters.find((parameter) =>
    parameter.toLowerCase().startsWith(BOUNDARY_PARAMETER)
  )
  if (!boundaryParameter) {
    return null
  }

  const boundary = boundaryParameter.slice(BOUNDARY_PARAMETER.length)
  const isQuoted =
    boundary.length > 1 && boundary.startsWith('"') && boundary.endsWith('"')
  const unquoted = isQuoted ? boundary.slice(1, -1) : boundary
  return unquoted || null
}

// Splits CRLF-separated lines into the line groups between exact delimiter
// lines. A body framed with bare LF has no line equal to a delimiter, so it
// yields no groups.
function splitMultipart(lines, boundary) {
  const delimiter = `--${boundary}`
  const closeDelimiter = `${delimiter}--`
  const groups = []
  let current = null

  for (const line of lines) {
    if (line === closeDelimiter) {
      break
    }
    if (line === delimiter) {
      current = []
      groups.push(current)
    } else {
      current?.push(line)
    }
  }

  return groups
}

// Reads header lines from `start` up to the first blank line. Header names are
// lower-cased, as HTTP header names are case-insensitive.
function readHeaders(lines, start) {
  const headers = {}
  let index = start

  while (index < lines.length && lines[index] !== '') {
    const line = lines[index]
    const separatorIndex = line.indexOf(':')
    if (separatorIndex <= 0) {
      throw unsupported()
    }
    const name = line.slice(0, separatorIndex).trim().toLowerCase()
    headers[name] = line.slice(separatorIndex + 1).trim()
    index++
  }

  return { headers, next: index + 1 }
}

function parseRequestLine(line) {
  const tokens = (line ?? '').split(' ')
  if (
    tokens.length !== REQUEST_LINE_TOKEN_COUNT ||
    tokens[2] !== HTTP_VERSION
  ) {
    throw unsupported()
  }

  const [method, url] = tokens
  let pathname
  try {
    pathname = new URL(url, URL_RESOLUTION_BASE).pathname
  } catch {
    throw unsupported()
  }

  const match = ENTITY_KEY_PATH_PATTERN.exec(pathname)
  if (!match) {
    throw unsupported()
  }

  return {
    method: method.toUpperCase(),
    url,
    entitySet: match[1],
    id: match[2]
  }
}

function parseJsonBody(bodyLines) {
  const text = bodyLines.join(CRLF).trim()
  if (text === '') {
    return null
  }

  try {
    return JSON.parse(text)
  } catch {
    throw new BatchParseError(ERROR_INVALID_JSON)
  }
}

function parseChangesetPart(lines) {
  const { headers: partHeaders, next: requestLineIndex } = readHeaders(lines, 0)
  if (partHeaders['content-type']?.toLowerCase() !== APPLICATION_HTTP) {
    throw unsupported()
  }

  const request = parseRequestLine(lines[requestLineIndex])
  const { headers, next: bodyIndex } = readHeaders(lines, requestLineIndex + 1)

  return {
    contentId: partHeaders['content-id'] ?? null,
    ...request,
    headers,
    body: parseJsonBody(lines.slice(bodyIndex))
  }
}

function parseParts(contentTypeHeader, bodyText) {
  const batchBoundary = getMultipartBoundary(contentTypeHeader)
  if (!batchBoundary || typeof bodyText !== 'string') {
    throw unsupported()
  }

  const batchParts = splitMultipart(bodyText.split(CRLF), batchBoundary)
  if (batchParts.length === 0) {
    return []
  }
  if (batchParts.length > 1) {
    throw unsupported()
  }

  const [changesetLines] = batchParts
  const { headers, next } = readHeaders(changesetLines, 0)
  const changesetBoundary = getMultipartBoundary(headers['content-type'])
  if (!changesetBoundary) {
    throw unsupported()
  }

  const changesetParts = splitMultipart(
    changesetLines.slice(next),
    changesetBoundary
  )
  if (changesetParts.length > MAX_BATCH_PARTS) {
    throw new BatchParseError(ERROR_TOO_MANY_PARTS)
  }

  return changesetParts.map(parseChangesetPart)
}

/**
 * Parses a Dataverse `$batch` request holding a single changeset.
 *
 * Lines are split on CRLF only, so a body framed with bare LF yields zero
 * parts rather than an error. Part URLs may be absolute or relative, and must
 * address one record as `/api/data/v9.2/<entitySet>(<id>)`.
 *
 * @param {string | undefined} contentTypeHeader - the request Content-Type
 * @param {string} bodyText - the raw request body
 * @returns {{ parts: Array<{ contentId: string | null, method: string, url: string, entitySet: string, id: string, headers: Record<string, string>, body: unknown }> } | { error: 'unsupported' | 'invalid_json' | 'too_many_parts' }}
 */
export function parseChangesetRequest(contentTypeHeader, bodyText) {
  try {
    return { parts: parseParts(contentTypeHeader, bodyText) }
  } catch (err) {
    if (err instanceof BatchParseError) {
      return { error: err.reason }
    }
    throw err
  }
}

const statusLine = (status) =>
  `${HTTP_VERSION} ${status} ${STATUS_CODES[status]}`

const defaultErrorBody = (status) => ({
  error: {
    code: STUB_ERROR_CODE,
    message: `${STUB_ERROR_MESSAGE_PREFIX} ${STATUS_CODES[status]}`
  }
})

function buildResponsePartLines(partResult, baseUrl) {
  const { contentId, status, entitySet, id, errorBody } = partResult
  const lines = [
    'Content-Type: application/http',
    'Content-Transfer-Encoding: binary'
  ]
  if (contentId !== null && contentId !== undefined) {
    lines.push(`Content-ID: ${contentId}`)
  }
  lines.push('', statusLine(status))

  if (status >= HTTP_BAD_REQUEST) {
    const body = errorBody ?? defaultErrorBody(status)
    lines.push(
      `Content-Type: ${ERROR_CONTENT_TYPE}`,
      'OData-Version: 4.0',
      '',
      JSON.stringify(body)
    )
    return lines
  }

  lines.push('OData-Version: 4.0')
  if (status === HTTP_NO_CONTENT) {
    lines.push(`OData-EntityId: ${baseUrl}/${entitySet}(${id})`)
  }
  lines.push('', '')
  return lines
}

/**
 * Builds a multipart `$batch` response for one changeset.
 *
 * When any part has failed, only the first failing part is included, as a
 * changeset commits nothing when one part fails. With no parts, the response
 * is an empty batch.
 *
 * @param {Array<{ contentId: string | null, status: number, entitySet: string, id: string, errorBody?: object }>} partResults
 * @param {{ baseUrl: string }} options - Web API base URL for OData-EntityId
 * @returns {{ contentType: string, body: string }}
 */
export function buildBatchResponse(partResults, { baseUrl }) {
  const batchBoundary = `batchresponse_${randomUUID()}`
  const contentType = `${MULTIPART_MIXED}; boundary=${batchBoundary}`

  if (partResults.length === 0) {
    return { contentType, body: `--${batchBoundary}--${CRLF}` }
  }

  const firstFailure = partResults.find(
    (partResult) => partResult.status >= HTTP_BAD_REQUEST
  )
  const includedParts = firstFailure ? [firstFailure] : partResults
  const changesetBoundary = `changesetresponse_${randomUUID()}`

  const lines = [
    `--${batchBoundary}`,
    `Content-Type: ${MULTIPART_MIXED}; boundary=${changesetBoundary}`,
    '',
    ...includedParts.flatMap((partResult) => [
      `--${changesetBoundary}`,
      ...buildResponsePartLines(partResult, baseUrl)
    ]),
    `--${changesetBoundary}--`,
    `--${batchBoundary}--`,
    ''
  ]

  return { contentType, body: lines.join(CRLF) }
}
