import { describe, test, expect } from 'vitest'
import {
  ODATA_ERROR_CONTENT_TYPE,
  STUB_ERROR_CODE,
  buildStubErrorBody
} from '../../src/utils/odata-error.js'

describe('#odata-error', () => {
  test('uses the OData minimal metadata JSON content type', () => {
    expect(ODATA_ERROR_CONTENT_TYPE).toBe(
      'application/json; odata.metadata=minimal'
    )
  })

  test('builds an error body marked as generated by the stub', () => {
    expect(buildStubErrorBody(412)).toEqual({
      error: {
        code: STUB_ERROR_CODE,
        message:
          'Generated by fcp-sfd-crm-stub, not Dataverse error text: Precondition Failed'
      }
    })
  })

  test('names the status in the message for any standard status code', () => {
    expect(buildStubErrorBody(400).error.message).toContain('Bad Request')
  })
})
